/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tensorflow_lite_examples_classification_ClassifierActivity */

#ifndef _Included_org_tensorflow_lite_examples_classification_ClassifierActivity
#define _Included_org_tensorflow_lite_examples_classification_ClassifierActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef org_tensorflow_lite_examples_classification_ClassifierActivity_PERMISSIONS_REQUEST
#define org_tensorflow_lite_examples_classification_ClassifierActivity_PERMISSIONS_REQUEST 1L
#undef org_tensorflow_lite_examples_classification_ClassifierActivity_TEXT_SIZE_DIP
#define org_tensorflow_lite_examples_classification_ClassifierActivity_TEXT_SIZE_DIP 10.0f
/*
 * Class:     org_tensorflow_lite_examples_classification_ClassifierActivity
 * Method:    BCHDecode
 * Signature: ([B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tensorflow_lite_examples_classification_ClassifierActivity_BCHDecode
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
